//! ABI-stable cdylib export for the smb storage backend.
//!
//! smb is a **backend-only** plugin, so its entire export is generated by the
//! toolkit's [`export_storage_plugin!`]: the metadata fns, the storage
//! `BackendDef` (derived from [`SmbBackend`]'s own `provider()` — kind,
//! endpoint and capabilities are never restated here), and the proxied-op
//! routing. The per-op `match` and the wire-arg structs that used to live in
//! this file now live once in `plugin_toolkit::storage` (`dispatch_op`), shared
//! by every storage backend.
//!
//! `abi_stable` remains the crate's one direct non-orca dep because
//! `#[export_root_module]` (which the macro invokes) expands to bare
//! `::abi_stable` paths.

plugin_toolkit::export_storage_plugin! {
    name: "smb",
    target_compat: "any",
    backend: crate::SmbBackend::new("smb"),
}
